### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by pierreozoux** [djmaze/maiilinabox-docker#2]
When I run the command `docker-compose run management add-initial-user`, I get the following exception. do you have an idea where it could come from?

Thanks!

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/mailinabox/management/daemon.py", line 49, in newview
    return viewfunc(*args, **kwargs)
  File "/usr/local/mailinabox/management/daemon.py", line 146, in mail_users_add
    return add_mail_user(request.form.get('email', ''), request.form.get('password', ''), request.form.get('privileges', ''), env)
  File "/usr/local/mailinabox/management/mailconfig.py", line 320, in add_mail_user
    return kick(env, "mail user added")
  File "/usr/local/mailinabox/management/mailconfig.py", line 561, in kick
    existing_alias_records = get_mail_aliases(env)
  File "/usr/local/mailinabox/management/mailconfig.py", line 186, in get_mail_aliases
    c.execute('SELECT source, destination, permitted_senders FROM aliases')
sqlite3.OperationalError: no such column: permitted_senders
```

**Comment by djmaze** [comment]
This is possibly because of an update to the mailinabox management interface. 

Unfortunately, the management container is built from the [latest master code](https://github.com/djmaze/mailinabox-docker/blob/master/management/Dockerfile#L7) currently, which is quite ugly. I am about to change this. Sorry for the mess.
